### ISSUE TITLE
loss output at intermediate inuring priorities - new features 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1468]
## Issue Description
Features that are still outstanding are;
- [ ] Net Loss Pre-Cat. Ability to request and output (intermediate) net perspective. The functionality implemented here provides reinsurance loss output only. Logic for linking this perspective to inuring priority number needs implementing.
- [ ] Grouping of reinsurance gross loss output in one consolidated set of outputs. Losses are output in multiple sets for each inuring priority number.
- [ ] Reinsurance loss by Contract. Support for summary levels which are requested for reinsurance gross output, for example, by Reinsurance contract (ReinsNumber) which involves adding support for OED fields from the ri info file. Moreover the list of OED fields for reinsurance gross perspectives may be different from those requested for GU, IL and RI (Net), which probably means additional parameters in analysis settings
- [ ] Ability to request additional financial perspectives and summary levels from user front end (API support). There is no ability to request the extra perspectives from the front end yet.

> From: https://github.com/OasisLMF/OasisLMF/pull/1458#issuecomment-1971498747

**Comment by johcarter** [comment]
Suggested changes to analysis_settings to drive outputs for additional reinsurance perspectives.

### Reinsurance loss
Reinsurance loss is a different perspective from reinsurance net (ri) so this should be broken out as a separate blob in analysis settings. Demonstrated using 'rl' for 'reinsurance loss' in the middle section. 
```
    "il_output": true,
    "il_summaries": [
        {
            "aalcalc": true,
            "eltcalc": true,
            "id": 1,
         }
    ],
    "rl_output": true,
    "rl_summaries": [
            "aalcalc": true,
            "oed_fields": ["ReinsNumber"]
            "id": 2
    ],
    "ri_output": true,
    "ri_summaries": [
        {
            "aalcalc": true,
            "eltcalc": true,
            "id": 1
            }
    ]
```
**"rl_output": true** means output ALL reinsurance loss outputs (instead of using the implemented "ri_inuring_priorities" param). Results sets will come out separated by inuring priority, but the complete financial perspective is all of them merged together.  I don't think you would ever require a partial output of this perspective (through using, for example, "ri_inuring_priorities": [1,3]).

The rl blob then supports a different summary level definition for rl through "oed_fields"  compared with gu, il, ri which is likely for reinsurance loss perspective.  Here we need to enable oed fields from the ri files to be used define summary levels, which is a requirement of this feature (e.g. reinsurance loss by contract output).

How the reinsurance output losses should be brought together I'm not sure yet, but I don't think it should be left to the user.  Perhaps a post processing component to aggregate the summarycalcs before downstream outputs?

### Net loss perspectives 
The new parameter ri_inuring_priority: [1,2] could be used to specify which intermediate net perspectives to generate.  This could belong within the ri_summaries:[] blob. The only requirement for now is the Net Loss Pre-Cat perspective which equates to a single inuring priority determined by the data in the ri_info file.     The user could select this perspective in the front end, and some logic would work out the correct number to populate into "ri_inuring_priorities": [] in analysis settings.  Then finally, in genbash we would need tee the fm stream for that ri cycle number to output the intermediate net results to files, as well as final ri net loss.

**Comment by johcarter** [comment]
@hchagani-oasislmf and I have defined the following tasks to kick off this work

- [ ] create new rl_outputs and rl_summaries parameters in analysis settings to drive all reinsurance loss perspective outputs
- [ ] relabel the existing reinsurance loss outputs to use the code rl rather than ri, but otherwise keep the same naming convention
- [ ] use existing ri_inuring_priorities parameter in analysis to drive new intermediate reinsurance net loss perspectives with output files labelled ri. This involves some genbash work to 'tee' the fmpy ri net stream to files as well as passing it down the pipe to the next RI calculation

As part of this work and to prepare for the UI controls, we are considering making changes to the run dir;

- [ ] move ri_layers.json into the inputs folder (so that the available net perspectives may be read by the UI)
- [ ] move RI_[X] folders from the root run dir to be nested in the inputs dir, and make the necessary changes to genbash to change the relative folder path of the RI_[X] folders in the run_ktools script.

@sambles  any concerns about the proposed run dir changes?  Moving the RI folders is not strictly needed but would make sense as they are part of the inputs to the calculation.

More work is needed to work out what further processing is needed to the output files to present them to users in the way they would expect them.

**Comment by benhayes21** [comment]
Latest changes to MDK branch feature/1468_intermediate_inuring_priorities. Outstanding issues:

 -   One test is failing.
 -   ri_layers.json and RI_*/ folders need to be moved to input/ directory.
