### ISSUE TITLE
CLI - Infer FM file generation based on analysis-settings

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#164]
Currently an FM flag is needed when running `GenerateLossesCmd` from the MDK 
```
 --fm                  Generate FM files - False if absent
```

Its probably cleaner to run the FM module based on the `analysis-settings.json`
rather than have an explicit flag

**Comment by sr-murthy** [comment]
This is as aspect of the initial implementation of the MDK model commands. The reason for doing it this way was that it was felt that it was clearer for the user to indicate the requirement of generating FM output files via the command line (via the flag), which would then be converted to a step in the model execution code where the analysis settings file is scanned for the FM analysis information. So with this way of implementing FM losses, the analysis settings should include the FM information, but you only get FM output files if the flag is passed during the command call.

There are advantages to this because the analysis settings is a static file that is loaded into memory, and if you've got a user who is trying out several runs then it would be easier for them to indicate they want FM outputs via the command rather than modifying the analysis settings file and then running the command. If they then switch between FM and GUL outputs they will have to update the file each time.

**Comment by sr-murthy** [comment]
Had a Slack discussion with @sambles. The keys point to note is

>... execution via the API is another way of using the MDK. It is also meant to be used as a standalone CLI. I think we have to balance the requirements for both modes of use.

The solution:

>...there are two modes of use for the commands: (1) standalone (command line) user and (2) API. If we make the FM flag optional (not required) in the Oasis files generation, loss generation and model run commands then the command code can have an `if` statement to get the FM option either via the flag for (1) or via the analysis settings file for (2).
