### ISSUE TITLE
unixodbc-dev package no longer a dependency when installing oasislmf?

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#176]
currently an undocumented dependency when installing oasislmf in linux, but perhaps this is no longer required in the api version

**Comment by sr-murthy** [comment]
@johcarter @sambles At the moment, `unixodbc-dev` system library and `pyodbc` Python library are required for the MDK package, because the API server (in OasisUI) uses the `oasislmf.utils.db` module for database transactions.

https://github.com/OasisLMF/OasisUI/blob/develop/src/flamingo_api_server/flamingo_db_utils.py#L4

This is that database module in the MDK package

https://github.com/OasisLMF/OasisLMF/blob/master/oasislmf/utils/db.py

So until you have a complete replacement of this, you need to keep those two packages as dependencies in the MDK.

**Comment by sr-murthy** [comment]
@johcarter @sambles At the moment, the `unixodbc-dev` system library and `pyodbc` Python libraries are required for the MDK package, because the API server (in OasisUI) uses the `oasislmf.utils.db` module for database transactions.

https://github.com/OasisLMF/OasisUI/blob/develop/src/flamingo_api_server/flamingo_db_utils.py#L4

This is that database module in the MDK package

https://github.com/OasisLMF/OasisLMF/blob/master/oasislmf/utils/db.py

So until you have a complete replacement of this, you need to keep those two packages as dependencies in the MDK.

**Comment by johcarter** [comment]
thats fine then, thanks Sandeep. Perhaps you could mention it as a GNU/Linux dependency in the README please? cheers Joh

**Comment by sr-murthy** [comment]
OK, I'll update the README in my current RI integration PR, which will go into the next release.

**Comment by sr-murthy** [comment]
README updated.
