### ISSUE TITLE
get_gul_input_items uses incorrect case for columns, resulting in dtype mismatches

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#204]
Running `oasislmf model run ...` in v1.3.2, I receive the following error at line 113 in `oasislmf.model_preparation.gul_inputs.get_gul_input_items`:

`2019-03-11 16:45:40,167 - root - ERROR - You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat`

This is because the `locnumber` column in `exposure_df` and `locid` column in `keys_df` are different, despite the calls to `get_dataframe` specifying datatypes for the columns. The issue arises because OasisLMF has converted the OED column names to all-lowercase at an earlier stage, but the calls to `get_dataframe` refer to them using cancelcase. Therefore, it is trying to convert the datatypes of the nonexistent `LocID` and `LocNumber` columns, rather than `locid` and `locnumber`.

(There's a lot of mixing of lowercase and camelcase in OasisLMF, so there may well be other, similar bugs hiding)

**Comment by sr-murthy** [comment]
@DanielFEvans There is no error here - that is a Pandas warning, and it is unrelated to any column casing issues. Execution should not be interrupted, but complete normally.

Which version of Python are you running the package in?

**Comment by DanielFEvans** [comment]
Python 2.7.5, with Pandas 0.24.1 (as required by OasisLMF). I think this only became an error more recently in Pandas (I think 0.23).

**Comment by sr-murthy** [comment]
@DanielFEvans That is relevant, because we know that there is a Pandas bug with 0.23.x

https://github.com/pandas-dev/pandas/issues/23733

which is why we upgraded the package to use Pandas to `0.24.x`. In fact, it should work with Pandas 0.22.0 as well, but Pandas `0.24.1` gets installed with the MDK.

We did not see any runtime errors in the CI testing phase with either Python 3.5+ or Python 2.7.

**Comment by sr-murthy** [comment]
@DanielFEvans It does look like the column datatypes setting step in `get_dataframe` will fail to take effect if the column case used by the caller does not match any lowercasing of the frame columns in `get_dataframe` as a result of `lowercase_cols=True`. That logic was correct prior to release 1.3.1, but  some changes were made by other developers, and as a result the column datatypes setting step is incorrect.

But this does not explain the warning you're seeing. That is a Pandas warning related to a bug in Pandas version 0.23.x, and my suggestion is to use either 0.22.0 or upgrade to 0.24.1. The merge of the exposure and keys files on the loc. number / loc. ID column is correct in the datatype, because loc. numbers / loc. IDs (the `LocNumber` column in the exposure file / `LocId` column in the Oasis keys file) are treated as strings.

As I said earlier, we have runtime and static tests of the MDK, for both Python 2.7 and Python 3.5+, and all tests passed.

**Comment by DanielFEvans** [comment]
@sr-murthy - I've modified gul_imports.py around line 113 as follows to illustrate the problem:

```...
        for df in [exposure_df, keys_df]:
            df['index'] = df.get('index', range(len(df)))

        print("Before expkeys_df merge")
        print("Python version: {}")
        print("Pandas version: {}".format(pd.__version__))
        print("exposure_df '{}' dtype: {}".format(loc_id, exposure_df[loc_id].dtype))
        print("keys_df 'locid' dtype: {}".format(keys_df['locid'].dtype))
        try:
            expkeys_df = merge_dataframes(exposure_df, keys_df, left_on=loc_id, right_on='locid', how='outer')
            print("Merge completed successfully")
        except Exception as e:
            print("Merge failed with following error: {}".format(e.message))
            raise

        cov_level = min(fm_levels)
        ...```

The output when I run `oasislmf model run -C oasislmf.json --verbose` is:

```Before expkeys_df merge
Python version: {}
Pandas version: 0.24.1
exposure_df 'locnumber' dtype: int64
keys_df 'locid' dtype: object
Merge failed with following error: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat
```

As you can see, I am on Python 0.24.1, and the `locnumber` column is not being treated as a string.

**Comment by sr-murthy** [comment]
@DanielFEvans Thanks, I'm reopening this issue. We got no runtime errors when doing runtime tests of the last release (or even 1.3.1) on our test model (PiWind) - it might be that you're using data which exposed that hidden problem with how the column data types were being set in the call to `get_dataframe`. 

We will release a hotfix at some point today.

**Comment by sr-murthy** [comment]
@DanielFEvans A hotfix has been released - tests were ran on some updated source files with string values for loc. numbers and they all passed. Please confirm whether it is OK at your end.

**Comment by DanielFEvans** [comment]
That looks good now, thanks. I suspect the problem became obvious as our lookup was returning `None` for LocID, due to similar problems with the capitalisation of columns not matching.
