### ISSUE TITLE
Further FM support for processing OED deductible and limit codes

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#278]
Currently the deductible and limit codes are read in but nothing is done with them.

Now that they are read in, we need to link codes to fmcalc rules where they exist. currently we could do the Franchise deductible (deductible code = 2) and regular limit (code = 0) , which is calcrule 3. 

0 | Regular
-- | --
1 | Annual Aggregate
2 | Franchise Deductible
3 | Non ranking excess Deductible is a deductible that does not rank (or   count) toward a maximum aggregate deductible
4 | Residual Deductible is a (normally lower) deductible that applies once a   maximum aggregate deductible is exceeded
5 | Homeowner's Deductible (CEA)
6 | Homeowner's Choice Deductible (CEA)

**Comment by sr-murthy** [comment]
For reference, here's the calc. rules static table that we use when generating calc. rules in the IL inputs generation phase

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/_data/calc_rules.csv

So there are no calc. rules involving non-zero deductible codes. It is quite simply a case of updating this CSV file, with the new calc. rules.

**Comment by sr-murthy** [comment]
I think this issue can be closed, because all the required calc. rules are supported, including the one you mention (franchise deductible + limit, 3)

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/_data/calc_rules.csv#L4

Calc. rule IDs are assigned to items in the IL inputs table based on a kind of merge lookup on the calc. rules dataframe, which is loaded from the calc. rules static data file above. No additional processing is required.

If there is a test case involving calc. rule ID 3 then you can add that to `validation/examples`.

**Comment by johcarter** [comment]
This is a longer term feature as we need to add more calcrules to ktools to support the various codes

**Comment by sr-murthy** [comment]
OK, that's fine. Adding calc. rules to the MDK is done by updating the static calc. rules CSV file, which is part of the package data. It doesn't involve or require any changes in the code.
