### ISSUE TITLE
Error Handling or raise exception in CalcRule mapping  

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#288]
If `il_inputs_calc_rules_df` contains NaN values:
```
   item_id  deductible  deductible_min  deductible_max         limit  ...  lim_code  lim_type limit_gt_0  share_gt_0  attachment_gt_0
0        1         0.0             0.0             0.0  0.000000e+00  ...       NaN       NaN        NaN         NaN              NaN
1        2         0.0             0.0             0.0  0.000000e+00  ...       NaN       NaN        NaN         NaN              NaN
2        3         0.0             0.0             0.0  0.000000e+00  ...       NaN       NaN        NaN         NaN              NaN
3        4         0.0             0.0             0.0  3.542550e+06  ...       NaN       NaN        NaN         NaN              NaN
4        5         0.0             0.0             0.0  3.542550e+06  ...       NaN       NaN        NaN         NaN              NaN
5        6         0.0             0.0             0.0  3.542550e+06  ...       NaN       NaN        NaN         NaN              NaN
6        7         0.0             0.0             0.0  1.000000e+10  ...       0.0       0.0        1.0         1.0              0.0
7        8         0.0             0.0             0.0  1.000000e+10  ...       0.0       0.0        1.0         1.0              0.0
8        9         0.0             0.0             0.0  1.000000e+10  ...       0.0       0.0        1.0         1.0              0.0
``` 
at  https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/model_preparation/il_inputs.py#L116 , then there is a mismatch between the input exposure and https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/_data/calc_rules.csv 

This probably indicates an error with the input files so either:
1) warn the user and continue 
2) raise exception and exit

**Comment by johcarter** [comment]
This was caused by DedType = 1 and Ded = 0 (for all location coverages 1-6)
Valid values for Ded is <=1 including zero, regardless of DedType. So the user input in this case is valid.

The expected behaviour is to regard Ded=0 as no deductible, regardless of the value in the DedType field, and assign the appropriate calcrule based on no deductible being present, rather than fail as described above.

This logic extends to limit type because Limit = 0 and LimitType = 1 (or 2) are valid user inputs according to the OED spec. Limit = 0 means no limit for all Types.

**Comment by sambles** [comment]
For reference:
https://github.com/OasisLMF/OasisLMF/pull/286
