### ISSUE TITLE
CountryCode "NA" is converted to None

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#307]
We are attempting to run a test portfolio that includes aggregated risks in every country in the world. Location number 156 in this portfolio is Namibia, with the ISO Alpha 2 country code "NA", which is listed as permitted in the OED Exposure Data Spec.

By the time the OED locations data is passed to our lookup code, the data is as follows:
```
locnumber  accnumber  portnumber countrycode locperilscovered  ...
156          1           1        None      OO1;ORF;OSF  ...
157          1           1          NC      OO1;ORF;OSF  ...
158          1           1          NE      OO1;ORF;OSF  ...
```

The data should instead be:
```
locnumber  accnumber  portnumber countrycode locperilscovered  ...
156          1           1          NA      OO1;ORF;OSF  ...
157          1           1          NC      OO1;ORF;OSF  ...
158          1           1          NE      OO1;ORF;OSF  ...
```

This is likely caused by a call to `pandas.read_csv`, which default treats the string `"NA"` as indicating nodata by default.

(Behaviour occurs in OasisLMF v1.3.10)

**Comment by sr-murthy** [comment]
@DanielFEvans This is because when reading the CSV Pandas parses values to see if they are in a set default null values, it considers to be null, which includes the string `NA`:

    ['-1.#IND', '1.#QNAN', '1.#IND', '-1.#QNAN', '#N/A N/A', '#N/A', 'N/A', 'n/a', 'NA', '#NA', 'NULL', 'null', 'NaN', '-NaN', 'nan', '-nan', '']

This if from https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#na-values.

This is a relatively simple fix - we have to supply our own default NA values list (using the `na_values` option) which doesn't contain the string `NA` and tell it to ignore the default NA values list (using the `keep_default_na` option)

    pd.read_csv(...,keep_default_na=False, na_values=['-1.#IND', '1.#QNAN', '1.#IND', '-1.#QNAN', '#N/A N/A', '#N/A', 'N/A', 'n/a', '#NA', 'NULL', 'null', 'NaN', '-NaN', 'nan', '-nan', '']...)

**Comment by sr-murthy** [comment]
I've just pushed a fix for this on a  branch, which will be merged into `develop` shortly.

It should fix your problem, although because of the way it is implemented (excluding the string `NA` from being parsed as a null value anywhere in the file) it means that if you're using `NA` (regardless of case) to denote nulls in columns other than `CountryCode` and are expecting those values to be parsed as nulls then this won't work.

There is a way of specifying what values to consider as nulls in a column-wise way (using a dict for `na_values` in `read_csv` with the keys being column names and values being the set of values to consider as nulls for those columns), but for the moment this should be sufficient.

**Comment by DanielFEvans** [comment]
Thanks for the speedy response!

**Comment by sr-murthy** [comment]
Please confirm the fix in `develop` works.

**Comment by DanielFEvans** [comment]
I'm sorry to say it doesn't. On the line:

`na_values = list(PANDAS_DEFAULT_NULL_VALUES.difference('NA'))`

the argument to `difference` should be an iterable (i.e. `['NA']`, not `'NA'`).

**Comment by sr-murthy** [comment]
OK, yes that was a typo.

**Comment by sr-murthy** [comment]
Please use the branch `fix/get-dataframe-typo` to test at your end.

**Comment by DanielFEvans** [comment]
Yes, working now. Thanks.
