### ISSUE TITLE
more  issues in fm file generation for reinsurance and multiple direct layers

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#312]
I'm getting a seg fault for fmcalc (RI_1) when running the released version of oasislmf against the develop branch of OasisPiWind. It also appears to be broken in oasislmf fix/fm-acceptance-tests.
In fix/fm-acceptance-tests then:
The problem is to do with direct layers (PiWind Acc has 2) and the from agg_ids in the fm_programme for RI_1. The output_ids are 1-80 from direct, but fm_programme has 1-40 duplicated x2 for level 1.

To replicate run this against OasisPiWind develop branch
$oasislmf model run --config tests/oasislmf-ril-test.json

this results in a seg fault for the pipe fmcalc -a 2 -n -p RI_1
fmcalc: Segment fault at address: 0x7fb60c011618
fmcalc: Segment fault at address: 0x7f9c21815618

looks like the error might be on the reinsurance side.

note that OasisPiWind master needs to be updated from develop to be in line with the released version. 

Issue raised by GC (released version of package) but is also broken in fix/fm-acceptance-tests
fyi
@mpinkerton-oasis @sr-murthy

**Comment by sr-murthy** [comment]
This can be discussed next week with @mpinkerton-oasis next week.

Note, the issue with PiWind `develop` diverging from `master` is that `develop` was updated to support the recent change in the `develop` branch of the MDK which involved updating the code to process locations using a new internal `loc_id` column (a composite index on portfolio num., acc. num., loc. num.) rather than using `locnumber` file column. MDK `develop` has this change, but it's not part of any release.

PiWind `master` hasn't been updated because that would break PiWind CI builds which I'm guessing use MDK `master` (tracks releases). So we need to wait until the next MDK release before updating PiWind `master`.

Also, note that I'm confident that the direct input files are being generated correctly for PiWind `develop` on this fix branch (`fix/fm-acceptance-tests`) - you can test this by removing the RI input and scope files in the PiWind MDK config. file (or from the command line arguments if you're running PiWind with command line arguments, not config.) and running it. It runs fine.

**Comment by johcarter** [comment]
ok, so I have checked in PiWind10 as an fm test case in  OasisLMF/validation/examples/piwind10   develop branch.
It has two policy layers and no location terms.

I'm still seeing the same error in RI_1/fm_programme.csv as before.
from_agg_ids for level 1 are 1-30 repeated twice, whereas it should be from_agg_ids 1-60.
The direct fm files appear correct, with output_ids 1-60.

to replicate, run 
$ oasislmf exposure run -s validation/examples/piwind10

you'll also see the results output to the console look wrong, as they are missing layer 2 losses.
@mpinkerton-oasis FYI

**Comment by mpinkerton-oasis** [comment]
I'm seeing the correct agg ids in the RI_1/fm_programme.csv. The test files don't look correct though - plicy 2 has a very high attachment hence 0 losses, and the account numbers in the ri_scope file don't match the exposure.

**Comment by johcarter** [comment]
also the location number didnt match in the scope file. I have now corrected both.
The Surplus share now applies to the second and third location.  For the second, it is for PolNumber=Layer1 only. For the third, it is for Polnumber=Layer2.  This filter is not being applied, the ceded percent is being applied to both Layer1+Layer2 at level 2.

**Comment by johcarter** [comment]
Moving to new issue

**Comment by mpinkerton-oasis** [comment]
Closing original as not a bug and creating new issues for filter.

**Comment by johcarter** [comment]
there is still the issue of PiWind master lagging behind . The input files have been corrected in PiWind develop. will create a new issue
