### ISSUE TITLE
OasisLMF hangs if a subtask of `write_gul_input_files` fails

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#338]
We were running an analysis in OasisLMF and had reached  `oasislmf.model_preparation.write_gul_input_files`, and in particular the output of the items, coverages, etc. files was occurring, i.e. the lines:

```
for _, _ in multithread(tasks, pool_size=len(gul_input_files)):
    pass
```

At least one of those tasks failed as the machine ran out of disk space. I would have expected an exception to be raised and for OasisLMF to have exited. Instead, there was no relevant entry in the log file, and OasisLMF was still "alive", waiting for the return of a thread that had no longer existed.

Looking at `oasislmf.utils.concurrency.multithread`, I'm wondering if there's any handling of exceptions at all, given that it uses plain `Thread` objects? I don't think exceptions occurring within a `Thread` get passed back automatically, unlike higher level constructs like `multiprocessing.Pool`.

**Comment by sr-murthy** [comment]
@DanielFEvans ATM there is no thread exception handling. In fact, I will be removing the multithreading element entirely from the input file writing code, because of some problems with that step of input files generation in a separate context (performance testing). As you know the Python global interpreter lock (GIL), which prevents multiple threads from accessing the interpreter at the same time, means that you may as well write the files serially, and it will probably be just as fast, if you choose the right chunk size.

So I will be doing this shortly in a separate PR, which I will merge into `develop` later today.

**Comment by DanielFEvans** [comment]
A good solution!

**Comment by sr-murthy** [comment]
`develop` has been updated to remove concurrency from the input files generation. I'll close this issue if you can confirm your problem is solved. With very large files you can experience slowness during the file writing stage.

**Comment by sr-murthy** [comment]
@DanielFEvans Can you please confirm that the fix in `develop` now solves your problem?

**Comment by DanielFEvans** [comment]
Hi Sandeep, difficult one to reproduce - we've long since cleared out the full hard drive! I had some thoughts about intentionally raising an exception in the output code, but haven't had the time to delve into the OasisLMF code to add one.

**Comment by sr-murthy** [comment]
In that case I will close the issue, as it may well be a one-off. I think removing multithreading and using just serial writing should get rid of any threading problems. If it re-occurs you can reopen it.
