### ISSUE TITLE
Reinsurance Layer Logic

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#382]
Example: 
https://github.com/OasisLMF/OasisLMF/tree/develop/validation/examples/QS0506

Unnecessary layers created (based on ReinsNumber)
https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/model_preparation/reinsurance_layer.py#L821-L825

@johcarter 

Branch:  https://github.com/OasisLMF/OasisLMF/tree/fix/382-reins-layer-logic

**Comment by johcarter** [comment]
Unneccessary layers are being created when there are multiple reinsurance numbers applying to different distinct portfolios, accounts, locations (generally, "risk") with common inuring priority and risk level. it is only necessary to increment layer if more than one reinsurance number applies to the same risk for the same risk level and inuring priority.

In order to decide when to increment layer_id, you can use the following grouping of fields and look for duplicates in the scope file. Wherever you see a duplicate, that is when you increment layer_id over ReinsNumber. 

RiskLevel | grouping key
-- | --
LOC | PortNumber, AccNumber, LocNumber, InuringPriority
POL | PortNumber, PolNumber, InuringPriority
ACC | PortNumber, AccNumber,    InuringPriority
(blank) | PortNumber, AccNumber, PolNumber, LocGroup, LocNumber, InuringPriority

In the attached examples, fm_24 has genuine layers because there are duplicates of the above keys.  This is currently being modelled correctly.

in QS0506, there are no duplicates in ri scope, hence there should be no layer_ids above 1.  In the current implementation, we are generating 2 layers.

[example_fm24.xlsx](https://github.com/OasisLMF/OasisLMF/files/3530073/example_fm24.xlsx)
[example_QS0506.xlsx](https://github.com/OasisLMF/OasisLMF/files/3530074/example_QS0506.xlsx)

@sambles

**Comment by johcarter** [comment]
@mpinkerton-oasis I think I've found a short term fix for this problem.  
The problem affects multiple QS with equal inuring priority and RiskLevel=(blank). 

In other reins types and risk level examples, level 1 (risk level grouping) losses are all passed through using policytc_id 2, and risk terms are applied at level 2 (also risk level grouping).  Any risks not in scope will be given a policytc_id of 1 (0 limit) at level 2.

By contrast for QS RiskLevel (blank), level 1 (location or locaton-policy grouping) losses are passed through or set to zero depending on if they are in or out of scope using policytc_id 2 or 1 respectively. level 2 is grouping across all risks where treaty terms are applied (% ceded) and level 3 occurrence terms are equivalent.

The short term fix is to change QS RiskLevel (blank) to copy the structure of the other combos.  Pass through all losses at level 1 , maintain the risk grouping at level 2 and apply treaty terms (This can only be % ceded i think, without a RiskLevel specified) and then level 3 occurrence terms unchanged. 

(if this assumption is not correct, we could try adding an extra level 3 to group to treaty level and have the occurrence terms at level 4. the crucial bit appears to be avoiding setting zero limit at level 1 for out of scope risks. )

So, take a look at QS47_x2 which is two non-overlapping Quota shares with RiskLevel =(blank). You will see the error in the results because none of the second reins locations have any ri loss and gr=net.  I have demonstrated the fix to the input files in the expected folder, which produces the correct results (see raw ri1).

I suspect that this problem may also affect CATXL, as by definition, SS, PR and FAC must have a risk level specified, but CAT XL generally won't. To test.

We should still plan to reduce unnecessary layers as it is unscaleable and makes fmcalc look alot slower than it will be with files created appropriately with regards to layers.

**Comment by johcarter** [comment]
@benhayes21 fyi

**Comment by johcarter** [comment]
I've added the 4 level version of fix in this spreadsheet. @benhayes21 . The 3 level version is in the expected folder with the correct results, but the 4 level should produce the same results.
[comparison of input files QS47_x2.xlsx](https://github.com/OasisLMF/OasisLMF/files/3569274/comparison.of.input.files.QS47_x2.xlsx)

**Comment by mpinkerton-oasis** [comment]
@johcarter does this get folded into the general RI fix that Ben is working on? As discussed, there may be a performance optimization to collapse layers in some cases.

**Comment by mpinkerton-oasis** [comment]
@johcarter assume this can now be closed?
