### ISSUE TITLE
PiWind example fails on Python 3.6 because of dictionary comparisons

### ISSUE THREAD

**Issue by ElliotJH** [OasisLMF/OasisLMF#41]
When testing the PiWind example I ran into problems when a list of dictionaries gets sorted in oasislmf/exposures/manager.py, line 464. Python 2 is happy to sort such a list, but Python 3 is not.

I don't have a good intuition for why this sort is being performed but I'm guessing the goal is to impose an order on the output DataFrame?

The error I see currently is:

```
...
Generating Oasis files for model
Traceback (most recent call last):
*snip*
  File "/Users/user/oasis-lmf/OasisLMF/oasislmf/exposures/manager.py", line 593, in generate_oasis_files
    data_frame = self.load_master_data_frame(**kwargs)
  File "/Users/user/oasis-lmf/OasisLMF/oasislmf/exposures/manager.py", line 464, in load_master_data_frame
    filter(lambda v: v.get('FieldName') == 'TIV', six.itervalues(canonical_exposures_profile))
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

I tried a fix in https://github.com/OasisLMF/OasisLMF/compare/master...ElliotJH:python36-dict-comparison but I'm not clear why the sort is being performed so that key may be no good.

**Comment by sr-murthy** [comment]
@ElliotJH Yes, this came up during testing. In fact, in the original version of the code `six` wasn't being used, as any dict has `itervalues`. You can do the following
```
tiv_elements = tuple(sorted(
                [v for v in cep.itervalues() if v.get('FieldName') and v['FieldName'] == 'TIV'],
                key=lambda v: v['FMTermGroupID']
            ))
```
The sort is required because the point is to extract an list of TIV elements/fields (these are dict values in `cep` describing TIV elements which correspond to TIV fields, and these TIV fields describe column names in a CSV exposures file). The point is that the output of this line should be a list of TIV element dicts ordered element names, so for PiWInd the element for `WSCV1VAL` should be listed before the one for `WSCV4VAL`, etc.

**Comment by sr-murthy** [comment]
You can check that the code line I pasted above does work on Python 3.6

**Comment by sr-murthy** [comment]
@ElliotJH It appears I was wrong - Python 3.6 dicts don't have `itervalues`, instead have `values` which appear to be generators. I mainly develop in Python 2.7, and am less familiar with 3+. So the issue you pointed out is still valid. In fact the solution is as follows

    tiv_elements = tuple(
        sorted(
            [v for v in canonical_exposures_profile.values() if v.get('FieldName') == 'TIV'],
            key=lambda v: v['FMTermGroupID']
        )
    )

So `filter` in Python 3 produces a generator not a list as in Python 2, so your solution wouldn't work.Tthe common solution is to replace the filter with a plain list, and loop over `<dict>.values()` not `<dict>.itervalues()`.

This will be fixed in the next release.
