### ISSUE TITLE
setup.py fails when behind a proxy

### ISSUE THREAD

**Issue by ibailey-SCOR** [OasisLMF/OasisLMF#477]
Proxy does not seem to be inherited from pip into setup.py, so when you try to install from the package folder like 
```
pip install . --proxy $HTTP_PROXY
```
... it will not install the package because it won't be able to download the ktools part.

https://github.com/OasisLMF/OasisLMF/blob/29d4b8be03eced79c8ac05d0e80e18161cefb684/setup.py#L70

Furthermore, timeout is set to 5000 seconds, which means it just hangs.

Preferred behavior would be...
1 - shorter timeout
2 - continue and finish the installation with a warning if the download fails

**Comment by sambles** [comment]
* I've reverted the change related to `http_proxy` `https_proxy`  so that should be picked up again. (http works, but https might need some tweaking)
* Fix the excessive timeout value

I'm reluctant to continue the installation with a warning because a user would only see the warning if they pip install with the `--verbose` flag.
