### ISSUE TITLE
Change handling of  LayerParticipation =0 to mean 0 not 1

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#573]
When LayerParticipation = 0, apply share of 0
When LayerParticipation is missing, apply share of 1 (or passthrough)

**Comment by hchagani-oasislmf** [comment]
The change is relatively simple: `_data/default_fm_profile_field_values.json` L23 needs to be changed to:

```
        "share": {"condition": ".notna()", "default_value": 1.0},
```

However, getting the accounts dataframe in `model_preparation/il_inputs.py:get_il_input_items()` calls `utils/data.py:get_dataframe()`, where in L490-498:

```
            df = pd.read_csv(
                src_fp,
                float_precision=float_precision,
                memory_map=memory_map,
                keep_default_na=False,
                na_values=na_values,
                dtype=col_dtypes,
                encoding=use_encoding
            )
```
`keep_default_na=False` causes any missing values default to 0. Therefore, if `LayerParticipation` is missing, it is read in as 0 anyway. Interestingly, because of this it would appear as though using the `col_defaults` argument for columns that do exist has no effect as none of these columns will be read in with NaN values.

**Comment by johcarter** [comment]
A suggested approach to try is defaulting missing values of LayerParticipation to 1 rather than 0.  All floats are blanket set to 0 in the code.

Then we can remove the default setting of LayerParticipation in default_fm_profile_field_values.json. 

This means that the LayerParticipation would remain as zero if set to zero in the input files (and generate zero loss), rather than currently being converted to 1 if it is missing or zero (invoking passthrough calcrule).

If this works then it would make the default_fm_profile_field_values.json redundant i think.

This feature makes it easy for users to 'zero' out an account rather than change the input files

**Comment by hchagani-oasislmf** [comment]
This is a good idea. In fact, the default values for the OED mapped FM terms are given in `_data/acc_dtypes.json` and `_data/loc_dtypes.json`, which can be pulled out. I think this would be better than hard coding them in. `LayerParticipation` is the only one of these fields with a default value of 1.

**Comment by johcarter** [comment]
Yes, agreed Hassan
