### ISSUE TITLE
fm file generation issues with fac when combined with other types of reinsurance

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#724]
When facultative reinsurance is combined with another type of reinsurance, such as CXL, with the same risk level  and inuring priorities (such that they get processed in the same set of files), the layers are not being generated for the non-fac reinsurance contracts, and the numbers are wrong.

This issue was probably introduced when we eliminated unnnecessary layers from facultative insurance, to process them all in one layer. This will work if there is only facultative types in the set of files, but we still must have different layers for other reinsurance types in the same set of files. 

Example to be provided

**Comment by hchagani-oasislmf** [comment]
The bug appears when a non-FAC contract precedes a FAC contract in `ri_info.csv`. As suggested by @johcarter, this was an oversight when fixing https://github.com/OasisLMF/OasisLMF/issues/598. This should be fixed by introducing a check to establish whether the previous contract is FAC or non-FAC and incrementing the layer ID accordingly.
