### ISSUE TITLE
Install error 1.1.24

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#73]
```
Installing collected packages: oasislmf
  Compiling /tmp/pip-install-MCQFe6/oasislmf/oasislmf-1.1.24.data/purelib/oasislmf/utils/keys_data.py ...
    File "/tmp/pip-install-MCQFe6/oasislmf/oasislmf-1.1.24.data/purelib/oasislmf/utils/keys_data.py", line 99
      return keys_records(from_peril_ids=just(peril_id), from_coverage_type_ids=just(coverage_type_id) min_size=min_size, max_size=max_size)
                                                                                                              ^
  SyntaxError: invalid syntax
  

Successfully installed oasislmf-1.1.24
Cleaning up...
```

**Comment by sr-murthy** [comment]
This looks like a warning, but a fatal error. Nevertheless, the module `utils/keys_data.py` is an outdated version of the tests data module (`tests/data.py`) and should be deleted from the repository and any local versions should also be removed.

**Comment by sr-murthy** [comment]
This file should already have removed from the repository, because the tests data module `data.py` was introduced many versions ago. So it must have come back in from someone who accidentally added this file when contributing to a subsequent release. That's why it is always good to run `git status -uno` before making any commits - that will show a list of files in the Git index marked for the next commit, and any unnecessary or irrelevant files can then be removed from the index.

**Comment by mpinkerton-oasis** [comment]
Is this resolved?

**Comment by sr-murthy** [comment]
Yes, I think so.

**Comment by sr-murthy** [comment]
Didn't see this with the 1.1.25 installation test I did yesterday.
