### ISSUE TITLE
No parameter for source accounts file 

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#77]
For oasislmf model sub-commands, you can set the source accounts file in the json using  "source_accounts_file_path". This does not seem to be available or documented as a command line switch.

**Comment by sr-murthy** [comment]
This is not a bug. In `master` and `dev` the Oasis files generation and model run commands, which is what you are referring to, don't look for any accounts or FM related parameters, because this is part of the FM PR, which is the production release of oasislmf doesn't have this feature either - it is only meant to generate GUL.

**Comment by sr-murthy** [comment]
@mpinkerton-oasis I don't know whether you were referring to the version of the model subcommands in the FM branch or the main branches. As I said the main braches don't contain any FM stuff. But in the FM branch there is an option for specifying the source accounts file for both the Oasis files generation and model run commands:
```
       ...
        parser.add_argument('-y', '--source-accounts-file-path', default=None, help='Source accounts file path')
```
In both commands the option short flag is `y` and long flag is `--source-accounts-file-path`. You can see this here

https://github.com/OasisLMF/OasisLMF/blob/feature/mdk-fm/oasislmf/cmd/model.py#L461

https://github.com/OasisLMF/OasisLMF/blob/feature/mdk-fm/oasislmf/cmd/model.py#L794
