### ISSUE TITLE
Overly generic exception message

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#80]
The following exception is thrown in many circumstances when running "model run" or "model generate_oasis_files", for example when the specified config file does not exist. It would be useful to have more specific error messages:

Either the lookup config JSON file path or the keys data path + model version file path + lookup package path must be provided

**Comment by sr-murthy** [comment]
This is thrown in in the `generate-oasis-files` model command. It is related to the resources required to load of the model lookup. As there are two types of lookup - the built-in lookup which is driven by the config JSON and the custom lookup which requires the keys data path, model version file path and lookup package path - all these arguments are parsed for, and depending on whether the first or second group of arguments is present entirely the relevant lookup is instantiated.

I think the problem is not specificity but the message not explaining the fact that the built-in lookup requires the config file and that the custom lookup requires the keys data path, model version file path and lookup package path. This can be part of the next release.
