### ISSUE TITLE
Max Ded back allocation

### ISSUE THREAD

**Issue by sstruzik** [OasisLMF/OasisLMF#803]
In the FM computation loss is not back allocated if it comes completely from the triggering of Max deductible and the two level below the Max deductible policy return 0 loss.
There is also some issue with the back allocation where loss are attributed to the "wrong" item.

test cases pointing out the issue:

[max_ded_issue.zip](https://github.com/OasisLMF/OasisLMF/files/6242891/max_ded_issue.zip)
[](url)

[max_ded_issue_functional.zip](https://github.com/OasisLMF/OasisLMF/files/6286633/max_ded_issue_functional.zip)

**Comment by sstruzik** [comment]
[max_ded_issue.zip](https://github.com/OasisLMF/OasisLMF/files/6242891/max_ded_issue.zip)
[](url)

**Comment by johcarter** [comment]
The main issue here causes some gross loss samples to be lost for allocrule 2, leading to policy losses on the low side for those policies with a max deductible in their hierarchy. In the example I have been looking at, 3 accounts run against PiWind, AAL is lower by 0.43% for those accounts. The effects could be larger or smaller for a different case, depending on many factors - it is not possible to say how material it is for each individual case.  However it is possible to measure the impact by running the same analysis using allocrule 1 and comparing results. allocrule 1 is working correctly.

**Financial terms that trigger this issue**
It can happen whenever there are prior level deductibles followed by a max deductible further up the heirarchy.
For example you could have one or more of LocDed1-4, LocDed5PD, LocDed6All, CondDed6All followed by one of LocMaxDed5PD, LocMaxDed6All, CondMaxDed6All, PolMaxDed6All.

**What is happening**
When normal deductibles reduce a sampled loss to zero, this zero loss is passed through to the maximum deductible (usually the policy max). If the maximum deductible is triggered, the loss increases and the carried deductible is reduced to the maximum deductible. The gross loss is calculated correctly at this stage.

When it comes to back-allocating using the prior level losses (allocrule 2), all prior level losses are zero because the lower level deductibles have wiped them out. so 0% allocation percentages are being applied to the policy loss and the back-allocated loss comes out as zero. The calculation is clever enough to look back 2 levels to find some prior level losses to base back-allocation on, but if it finds all zeros there too, then losses come out as zero.

**Proposed solutions**
A simple way of solving the problem is to default the back-allocation to ground up loss basis whenever prior level losses are all zero. This is easy to understand and reproduce (and compare with a1 results).  Or we can look at a more sophisticated algorithm that respects prior level limits in the back-allocation logic, but harder to understand and reproduce numbers in a spreadsheet.

**Comment by johcarter** [comment]
There is also an issue for some samples with back-allocated losses exceeding the input loss (ground up loss) or the prior level limit. This occurs even with simple ground up loss back-allocation (a1). So the simple solution will not avoid this problem.

The agreed solution is to back-allocate in line with prior level losses (going back more than one level if necessary) and limit each back-allocated loss to the smaller of the input loss and any prior level limit.  Any excess loss (caused by the reapplication of a limit) is redistributed among the other items in proportion to the underlimit amount.

The underlimit amount is defined as the amount by which a loss can be re-adjusted upwards, respecting any prior level limits.  

Example 1
GUL = 50, Ded=20, Limit = 30
Loss = 30, Underlimit = 0 (Loss at limit)

Example 2
GUL = 40, Ded = 20, Limit = 30
Loss = 20, Underlimit = 10 (Loss is 10 below limit)

Example 3
GUL = 25, Ded = 20, Limit = 30
Loss = 5, Underlimit = 20 (Loss is 25 below limit, but cannot be adjusted upwards by more than 20 as it would exceed GUL)

The test case for this situation is fm63 in ktest/ftest
