### ISSUE TITLE
Generic model tests cases

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#81]
Add generic unit test suite for the model steps that can be included in cookie cutter and hooked in with test data as it is generated, to provide model developers with a pre-built test suite. This could/should tie in with the test data used for integration tests.

**Comment by sr-murthy** [comment]
I assume by "model steps" you mean the steps involved in running the `oasislmf model run` command. The main method that actually controls the backend logic for running a model via the package is partly in the model run command itself (`oasislmf.cmd.model.RunCmd`) and the `start_oasis_files_pipeline` method in the exposure manager (`oasislmf.exposures.manager.OasisExposuresManager.start_oasis_files_pipepeline`).

I've been thinking about the best way of implementing unit tests for these model subcommands, including model run. Initially, we should start with separate tests for `generate-oasis-files` and then `generate-losses`, because `run` basically is implemented as running those two commands in that order. Then we could implement a test for `model run` very simply. This would be the quickest way of implementing what you suggest.

The test data is dependent on the model - when running PiWind we need all the source files + canonical profiles (exp. + acc.), FM aggregation profile (if FM is required), lookup resources (keys data path, model version file path, lookup package path if using the old lookup framework, or a lookup config file if the lookup is a built-in lookup like PiWind). So provided the model developers can provide us with a basic set of these files we can customise the runtime test modules so that test data can be provided externally.
