### ISSUE TITLE
allow fm outputs at account level

### ISSUE THREAD

**Issue by sstruzik** [OasisLMF/OasisLMF#859]
## Issue Description
allow fm outputs at account level, this requirement needs better definition.

- [x] See with BA for a better definition of this task
- [x] create input test and ideally expected output relative to this task

**Comment by johcarter** [comment]
We think the requirement is to support account level financial terms rather than 'allow fm outputs at account level', interpreted as outputting gross loss broken down by account number in results. This feature is already supported by user defined summary levels by OED fields 'PortNumber','AccNumber' in the analysis settings json in the MDK, and custom outputs in the Oasis UI.

Specifically is the requirement to support fields starting with AccDed[] and AccLimit[] in the OED account file, which may apply to the grouped policy losses under each account where there are multiple policy layers?

The existing FM files don't support grouping of losses over policies within an account because each policy layer is represented by a distinct layer_id and aggregation of layer_id is not supported in fmpy.
 
There are two options;
1) Create a new iteration of fm for account level terms which runs after direct terms but before reinsurance terms. losses are output from direct terms by item by layer_id, at which point they can be aggregated by account, and account terms are applied in a single level calculation.

2) Change fmpy to support aggregation across layer_id and add the account level calculation as the final 'level' in the existing direct terms fm iteration.

The benefits of approach 1) is that no change is needed to fmpy and it only involves generating fm files differently and adding an extra iteration of fm into the model execution pipeline. We already have the framework to do this as we do multiple fm iterations for reinsurance. We would be able to support Coverages 1-6 account deductibles and limits, because losses are back-allocated to items in the first iteration.
The disadvantages are that we would not be able to support min and max account deductibles, or ensure that prior level limits are maintained. The information required to handle these is lost between iterations.   This is a Medium effort solution.

The benefits of approach 2) are that we could support account terms in the same iteration as prior level direct terms, although not coverages 1-5 because no back-allocation is performed. Coverages 1-5 are not are not yet supported for special conditions and policies. We could support min and max deductibles at account level for 6All coverages, and ensure prior level limits are maintained.
The disadvantage is that it does not fit with the design of fmpy which means making the code more complicated and is potentially a higher development and testing effort.

This requirement should probably be considered alongside the requirement to support coverages 1-5 to optimise development and testing effort.

Example to follow

**Comment by johcarter** [comment]
[oed_piwind_with_account_terms.zip](https://github.com/OasisLMF/OasisLMF/files/6701282/oed_piwind_with_account_terms.zip)

**Comment by johcarter** [comment]
Account level terms to support, following consultation with interested parties

AccDed6All
AccMinDed6All
AccMaxDed6All
AccLimit6All
AccDedType6All (supporting 0= monetary, 1= % loss and 2=% TIV deductibles)
AccLimitType6All (supporting 0= monetary, 1= % loss and 2=% TIV limits)

Here is an example of PiWind 10 locations OED files with added account level terms.  The worked example illustrates how we think the account terms should apply and what account loss should be produced for the Damage Ratio scenarios [0.25,0.5,0.75,1]

[worked example.xlsx](https://github.com/OasisLMF/OasisLMF/files/6930341/worked.example.xlsx)
[account_terms.zip](https://github.com/OasisLMF/OasisLMF/files/6930342/account_terms.zip)

**Comment by johcarter** [comment]
@sstruzik @benhayes21 
Implementation of account terms will require the following;

Change fmpy to support aggregation across layer_id and add the account level calculation as the final 'level' in the existing direct terms fm iteration.

There is a question over how the input files should look and how to invoke this calculation.  An extra level needs to be added to the direct insurance fm input files, and logic needs to be written to aggregate loss across layers before the final level calculation.  The attached zip contains 4 sets of input files to consider;
[input_w_account_terms.zip](https://github.com/OasisLMF/OasisLMF/files/6931848/input_w_account_terms.zip)
* input_no_account_terms (base case) - the input files generated from piwind with no account terms (https://github.com/OasisLMF/OasisPiWind/tree/master/exposure_data)
* input_w_account_terms_optionA - optionA target input files for piwind with account terms.  At level 3 Layer_id = 1 is dropped, and only records for Layer_id = 2 are included.  There could be an implicit rule to aggregate across layer_ids if only the final layer_id is present. 
* input_w_account_terms_optionB - optionB target input files for piwind with account terms.  At level 3 Layer_id = 0 which has an explicit special meaning to aggregate across all layers.  
* input_w_account_terms_optionC - optionC target input files for piwind with account terms. Both layers are carried into level 3 (with identical calcrule), but a command line switch could be added to tell the calculation to group losses across layer_ids at level 3. 
* Any other options that we might consider? 
As discussed, I can’t see any business reason that would require this logic at any level other than final level.
Back-allocation considerations
I think we would still want to back-allocate to item_id and layer_id and preserve the same output_ids. This would mean back-allocating account loss to layer first (new logic), and then back-allocating layer loss back to output_ids (existing logic)

**Comment by johcarter** [comment]
Development tasks:
- [ ] Agree approach to file gen and invoking the calculation (JC/SS/BH)
- [ ] Produce set of input files for development (JC)
- [ ] FM file gen (SS)
- [ ] calcrules reference file for account terms (JC)
- [ ] test harness for different combinations of account terms to add to validation tests (JC)
- [ ] modification of fmpy to support aggregation of layer losses in final level (SS)

**Comment by johcarter** [comment]
Files for development
[acc1.zip](https://github.com/OasisLMF/OasisLMF/files/7091518/acc1.zip)

More test cases in validation/insurance_account

For calcrules, use oasislmf/_data/calc_rules_direct.csv

**Comment by johcarter** [comment]
Updated example shows expected account loss for acc1.zip
[worked.example2.xlsx](https://github.com/OasisLMF/OasisLMF/files/7091578/worked.example2.xlsx)
